version: '3.8'

services:
  app:
    build:
      context: ./app  # Путь к папке с Dockerfile для app
    ports:
      - "5000:5000"  # Порт, на котором будет доступно ваше приложение
    depends_on:
      - record_service

  record_service:
    build:
      context: ./record_service  # Путь к папке с Dockerfile для record_service
    ports:
      - "5001:5000"  # Порт, на котором будет доступен сервис
