version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - record_service

  record_service:
    build:
      context: ./record_service
    ports:
      - "5001:5000"
    volumes:
      - -path-/records.json:/service/records.json 

volumes:
  data:

